# Autobahn Integration Configuration
# Configuration for delegated probabilistic reasoning and biological intelligence

autobahn:
  # Connection settings
  host: "localhost"
  port: 8080
  timeout: 5000  # 5 second timeout for requests
  max_retries: 3
  retry_delay: 1000  # 1 second delay between retries
  
  # Authentication (if required)
  auth:
    enabled: false
    api_key: ""
    
  # Delegation settings - which tasks to delegate to Autobahn
  delegation:
    fire_analysis: true
    consciousness_modeling: true
    bayesian_optimization: true
    uncertainty_quantification: true
    emotional_mapping: true
    pattern_recognition: true
    
  # Performance settings
  performance:
    max_concurrent_requests: 10
    batch_processing: true
    batch_size: 50
    caching_enabled: true
    cache_ttl: 3600  # 1 hour cache TTL
    
  # Biological intelligence settings
  biological:
    membrane_processing: true
    metabolic_computation: true
    atp_management: true
    ion_channel_coherence: true
    consciousness_emergence: true
    
  # IIT (Integrated Information Theory) settings
  iit:
    phi_calculation: true
    phi_threshold: 0.1
    temporal_integration: true
    spatial_integration: true
    
  # Oscillatory processing settings
  oscillatory:
    frequency_ranges:
      quantum_coherence: [1e-44, 1e-40]  # Planck scale
      molecular_vibration: [1e-15, 1e-12]  # Femtosecond
      neural_oscillation: [0.001, 100]  # Hz range
      cognitive_cycle: [0.1, 10]  # Seconds
    
    processing_modes:
      - "coherent_superposition"
      - "decoherence_collapse"
      - "metabolic_computation"
      - "consciousness_emergence"
      
  # Bayesian inference settings
  bayesian:
    prior_strength: 0.5
    likelihood_weighting: 0.8
    posterior_sampling: 1000
    mcmc_chains: 4
    
  # Uncertainty quantification settings
  uncertainty:
    confidence_threshold: 0.7
    uncertainty_propagation: true
    monte_carlo_samples: 10000
    sensitivity_analysis: true
    
  # Fire pattern analysis settings
  fire_analysis:
    pattern_complexity_levels: 5
    temporal_resolution: 0.001  # 1ms
    spatial_resolution: 0.01    # 1cm equivalent
    physics_simulation: true
    
  # Audio optimization settings
  audio_optimization:
    latency_target: 20  # 20ms target
    quality_threshold: 0.9
    realtime_processing: true
    adaptive_parameters: true
    
  # Monitoring and logging
  monitoring:
    performance_tracking: true
    latency_monitoring: true
    error_tracking: true
    consciousness_phi_logging: true
    
  # Debug settings
  debug:
    enabled: false
    log_level: "INFO"
    trace_requests: false
    save_intermediate_results: false

# Heihachi-specific settings for Autobahn integration
heihachi:
  # Fire interface integration
  fire_interface:
    autobahn_delegation: true
    realtime_consciousness: true
    emotional_feedback: true
    
  # Pakati integration with Autobahn
  pakati:
    consciousness_validation: true
    understanding_verification: true
    progressive_masking_autobahn: true
    
  # Audio processing integration
  audio_processing:
    consciousness_informed_synthesis: true
    biological_intelligence_dsp: true
    uncertainty_aware_generation: true
    
  # Performance targets
  performance_targets:
    fire_analysis_latency: 10  # ms
    consciousness_calculation: 15  # ms
    audio_optimization: 20  # ms
    end_to_end_latency: 50  # ms
    
  # Fallback settings
  fallback:
    enabled: true
    local_processing: true
    degraded_mode: true
    timeout_threshold: 1000  # 1 second 