# HuggingFace Integration Configuration

# General settings
huggingface:
  enable: true
  model_name: "facebook/wav2vec2-base-960h"
  api_key: null  # Set your API key here or use --hf-api-key CLI option

  # Analysis types
  genre_classification: true
  instrument_detection: true

  # Model settings
  genre_model: "anton-l/wav2vec2-base-superb-gc"
  instrument_model: "alefiury/wav2vec2-large-xlsr-53-musical-instrument-classification"

  # Processing options
  batch_size: 10        # Process audio in chunks of this size (seconds)
  max_audio_length: 600 # Maximum audio length to process (seconds)
  
  # Output options
  confidence_threshold: 0.6  # Minimum confidence to include in results
  top_k: 5                   # Return top K results for classifications

# Processing settings - optimized for HuggingFace models
processing:
  num_workers: 2             # Fewer workers as HF models are resource-intensive
  memory_limit_mb: 4096      # Increased memory limit for transformers
  gpu_memory_fraction: 0.8   # Fraction of GPU memory to use

# Cache settings
storage:
  cache_hf_models: true      # Cache HuggingFace models locally
  hf_models_dir: "../models" # Directory to store cached models 